import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Header";
import YMetrica from "@/external/YMetrica";
import { Suspense } from "react";
import YMetrircaHit from "@/external/YMetrircaHit";
// import { usePathname, useSearchParams } from "next/navigation";
// import { AnimatePresence, motion } from "motion/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const overlayVariants = {
  //   visible: { opacity: 1 },
  //   hidden: { opacity: 0 },
  // };

  // const pathname = usePathname();
  // const params = useSearchParams();

  return (
    <html lang="ru">
      <head>
        <YMetrica />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />

        <main>
          {/* <AnimatePresence>
            <motion.div
              variants={overlayVariants}
              initial="hidden"
              animate="visible"
              exit="hidden"
              key={params || pathname}
            > */}
          {children}
          {/* </motion.div>
          </AnimatePresence> */}
        </main>
        <footer>footer</footer>
        <Suspense fallback={<></>}>
          <YMetrircaHit />
        </Suspense>
      </body>
    </html>
  );
}
